[project]
name = "postgres-manager"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=2.23.3",
    "psycopg[binary]>=3.2.9",
]
